import 'package:flutter/material.dart';
import 'package:flutterapp/figma_to_flutterapp/generateditem_cardwidget/generated/GeneratedCardBorderWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generateditem_cardwidget/generated/GeneratedCardWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generateditem_cardwidget/generated/GeneratedMediaWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generateditem_cardwidget/generated/GeneratedVegetablesWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generateditem_cardwidget/generated/Generated43Widget.dart';

/* Component Item_Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedItem_CardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 177.0,
      height: 211.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCardWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.847457627118644;

                final double height =
                    constraints.maxHeight * 0.11848341232227488;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0903954802259887,
                      y: constraints.maxHeight * 0.7109004739336493,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedVegetablesWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.15254237288135594;

                final double height =
                    constraints.maxHeight * 0.09004739336492891;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0903954802259887,
                      y: constraints.maxHeight * 0.8530805687203792,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated43Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.6635071090047393;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMediaWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCardBorderWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
