import 'package:flutter/material.dart';
import 'package:flutterapp/figma_to_flutterapp/generatednavigationbarwidget/generated/GeneratedVectorWidget60.dart';
import 'package:flutterapp/figma_to_flutterapp/generatednavigationbarwidget/generated/GeneratedBackgroundWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component Navigation Bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNavigationBarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 96.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedBackgroundWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.014492753623188406;
                double scaleX = (constraints.maxWidth * percentWidth) / 6.0;

                double percentHeight = 0.125;
                double scaleY = (constraints.maxHeight * percentHeight) / 12.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.050724637681159424,
                      translateY: constraints.maxHeight * 0.6458333333333334,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget60())
                ]);
              }),
            )
          ]),
    ));
  }
}
