import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedbuttonsecondarywidget1/generated/GeneratedIconshoppingcartWidget5.dart';

/* Component Button/Secondary
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonSecondaryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(8.0),
      child: Container(
        width: 78.0,
        height: 40.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(8.0),
                child: Container(
                  color: Color.fromARGB(255, 11, 206, 131),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2564102564102564;

                  final double height = constraints.maxHeight * 0.5;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3717948717948718,
                        y: constraints.maxHeight * 0.25,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIconshoppingcartWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
