import 'package:flutter/material.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedORDERNOWWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedDISMISSWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedDWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedWhenplacinganordarselecttheoptionContactlessdeliverandt.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedNonContactDeliveriesWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedEllipse17Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediphone11promax1widget/generated/GeneratedEllipse14Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 308.07958984375,
                top: 483.887939453125,
                right: null,
                bottom: null,
                width: 458.8754577636719,
                height: 449.5784912109375,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 616.6787109375,
                top: 142.9483642578125,
                right: null,
                bottom: null,
                width: 280.8326110839844,
                height: 353.0001220703125,
                child: GeneratedEllipse15Widget(),
              ),
              Positioned(
                left: 293.0,
                top: -38.5,
                right: null,
                bottom: null,
                width: 178.49990844726562,
                height: 135.21868896484375,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 584.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 33.0,
                child:
                    GeneratedWhenplacinganordarselecttheoptionContactlessdeliverandt(),
              ),
              Positioned(
                left: 40.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 61.0,
                child: GeneratedNonContactDeliveriesWidget(),
              ),
              Positioned(
                left: 155.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08487172518375415;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 35.13689422607422;

                  double percentHeight = 0.044642857142857144;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 40.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.45652173913043476,
                        translateY: constraints.maxHeight * 0.45982142857142855,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 22.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 56.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 20.0,
                child: GeneratedORDERNOWWidget(),
              ),
              Positioned(
                left: 177.0,
                top: 825.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedDISMISSWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 63.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 39.81103515625,
                top: 81.199951171875,
                right: null,
                bottom: null,
                width: 23.160001754760742,
                height: 25.950000762939453,
                child: GeneratedDWidget(),
              )
            ]),
      ),
    ));
  }
}
