import 'package:flutter/material.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediconshoppingcartwidget/generated/GeneratedVectorWidget8.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediconshoppingcartwidget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediconshoppingcartwidget/generated/GeneratedVectorWidget6.dart';
import 'package:flutterapp/figma_to_flutterapp/generatediconshoppingcartwidget/generated/GeneratedVectorWidget7.dart';

/* Component icon/shopping-cart
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconshoppingcartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.714285691579183;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 17.14285659790039;

                  double percentHeight = 0.4285714626312256;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.285715103149414;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2142858107884725,
                        translateY: constraints.maxHeight * 0.20833333333333334,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0952380895614624;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      2.2857141494750977;

                  double percentHeight = 0.0952380895614624;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      2.2857141494750977;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.30952370166778564,
                        translateY: constraints.maxHeight * 0.7797619501749674,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget6())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0952380895614624;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      2.2857141494750977;

                  double percentHeight = 0.0952380895614624;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      2.2857141494750977;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7380952835083008,
                        translateY: constraints.maxHeight * 0.7797619501749674,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget7())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1428571343421936;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      3.4285712242126465;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07142861684163411,
                        translateY: constraints.maxHeight * 0.20833333333333334,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: 1,
                        scaleZ: 1,
                        child: GeneratedVectorWidget8())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
