import 'package:flutter/material.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedtabbarwidget/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedtabbarwidget/generated/GeneratedTabWidget2.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedtabbarwidget/generated/GeneratedTabWidget1.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedtabbarwidget/generated/GeneratedDividerWidget.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedtabbarwidget/generated/GeneratedTabSelectedWidget.dart';

/* Component Tab Bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabBarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 1.00,
            b: 0.00,
            c: 0.00,
            d: -1.00,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 414.0,
                height: 80.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 1.0;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) / 414.0;

                          double percentHeight = 1.0;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) / 80.0;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: 0,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedBackgroundWidget())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 276.0,
                        bottom: null,
                        width: null,
                        height: 80.0,
                        child: GeneratedTabSelectedWidget(),
                      ),
                      Positioned(
                        left: 138.0,
                        top: 0.0,
                        right: 138.0,
                        bottom: null,
                        width: null,
                        height: 80.0,
                        child: GeneratedTabWidget1(),
                      ),
                      Positioned(
                        left: 276.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: null,
                        width: null,
                        height: 80.0,
                        child: GeneratedTabWidget2(),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 80.0,
                        right: 0.0,
                        bottom: null,
                        width: null,
                        height: 1.0,
                        child: GeneratedDividerWidget(),
                      )
                    ]),
              ),
            )));
  }
}
