import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figma_to_flutterapp/generatedbuttontextwidget/generated/GeneratedActionWidget2.dart';

/* Component Button/Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonTextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 64.0,
      height: 18.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 1.2777777777777777;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.046875,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedActionWidget2(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
